/**
 * Regenerates `e2e/.env.example` from the service registry.
 *
 * Generated rather than hand-kept for one reason: a hand-kept example drifts,
 * and the failure is silent — a variable the code reads but the example never
 * mentioned looks like a missing credential nobody documented. The registry is
 * what the suites actually read, so it is also what the example must come from.
 *
 *   pnpm --filter @theokit/plugins-e2e env:example
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { SERVICES } from '../src/services.js'

const lines: string[] = [
  '# Live E2E credentials — copy to e2e/.env and fill in what you have.',
  '#',
  '# GENERATED by `pnpm --filter @theokit/plugins-e2e env:example`. Edit',
  '# e2e/src/services.ts, not this file.',
  '#',
  '# Nothing runs without E2E_LIVE=1, so a stray `pnpm e2e` cannot spend money',
  '# or send email. Every variable is optional: a service whose credentials are',
  '# absent SKIPS with a named reason instead of failing.',
  '',
  'E2E_LIVE=0',
  '',
]

for (const spec of SERVICES) {
  lines.push(`# ── ${spec.label} — ${spec.pkg} (via ${spec.provider}, ${spec.exercise})`)
  if (spec.caveat !== undefined) lines.push(`# ⚠ ${spec.caveat}`)
  for (const cred of [...spec.credentials, ...spec.target]) {
    lines.push(`#   ${cred.what}`)
    lines.push(`#   ↳ ${cred.where}`)
    lines.push(`${cred.name}=`)
  }
  lines.push('')
}

lines.push('# Optional: lights up the Groq STT backend in the voice suite.')
lines.push('# ↳ console.groq.com/keys')
lines.push('GROQ_API_KEY=')
lines.push('')

const target = join(import.meta.dirname, '..', '.env.example')
writeFileSync(target, lines.join('\n'))
process.stdout.write(`wrote ${target} (${SERVICES.length} services)\n`)
