/**
 * The two pieces #48 added: the config this plugin renders, and the verbs
 * drizzle-kit does not have.
 *
 * `tests/integration/drizzle-kit-grammar.test.ts` proves the rendered config is
 * one the real binary reads. These are the cheaper questions it does not answer:
 * what goes INTO the config, and what happens when the scripts it cannot replace
 * are not configured.
 */

import { describe, expect, it } from 'vitest'

import { buildDbCommands, renderDrizzleConfig } from '../src/cli/db.js'
import { resolveOptions } from '../src/options.js'

describe('renderDrizzleConfig', () => {
  it('carries the driver, url and both paths the caller declared', () => {
    const config = renderDrizzleConfig(
      resolveOptions({
        driver: 'postgres',
        url: 'postgres://user:pw@host:5432/app', // trufflehog:ignore — fixture, not a real DSN
        schemaPath: './src/db/schema.ts',
        migrationsPath: './src/db/migrations',
      }),
    )

    // `postgres` is OUR name; drizzle-kit's dialect is `postgresql` (#48).
    expect(config).toContain('dialect: "postgresql"')
    expect(config).toContain('schema: "./src/db/schema.ts"')
    expect(config).toContain('out: "./src/db/migrations"')
    expect(config).toContain('url: "postgres://user:pw@host:5432/app"') // trufflehog:ignore
  })

  it('says it is generated, so nobody edits a file that is rewritten each run', () => {
    const config = renderDrizzleConfig(resolveOptions({ driver: 'sqlite', url: 'file:app.db' }))
    expect(config).toMatch(/Generated by @theokit\/plugin-db-drizzle/)
    expect(config).toMatch(/rewritten/i)
  })

  it('refuses to write a config with no url instead of emitting a broken one', () => {
    // A config missing `dbCredentials.url` fails deep inside drizzle-kit, where
    // the message names drizzle-kit rather than the setting the caller omitted.
    expect(() => renderDrizzleConfig(resolveOptions({ driver: 'sqlite' }))).toThrow(/url/i)
  })

  it('escapes a url that would otherwise break out of the string literal', () => {
    // The config is generated source, so an unescaped quote in a password would
    // produce a file that does not parse — or worse, one that runs.
    const config = renderDrizzleConfig(
      resolveOptions({ driver: 'postgres', url: 'postgres://u:a"b\\c@h/db' }),
    )
    expect(config).toContain(JSON.stringify('postgres://u:a"b\\c@h/db'))
    expect(config).not.toMatch(/url: "postgres:\/\/u:a"b/)
  })
})

describe('the verbs drizzle-kit does not have', () => {
  for (const verb of ['seed', 'reset'] as const) {
    it(`${verb} runs the user's script rather than a nonexistent subcommand`, () => {
      const opts = resolveOptions({
        driver: 'sqlite',
        url: 'file:app.db',
        seedScript: './db/seed.ts',
        resetScript: './db/reset.ts',
      })
      const cmd = buildDbCommands(opts).find((c) => c.verb === verb)

      expect(cmd?.kind).toBe('user-script')
      const args = cmd?.buildArgs(opts) ?? []
      expect(args).toEqual([`./db/${verb}.ts`])
      // Not the passthrough shape: `drizzle-kit reset` is what 0.2.0 spawned, and
      // no version of drizzle-kit has ever had that subcommand.
      expect(args).not.toContain(verb)
      expect(args).not.toContain('--schema')
    })

    it(`${verb} fails naming the missing setting, not naming drizzle-kit`, () => {
      const opts = resolveOptions({ driver: 'sqlite', url: 'file:app.db' })
      const cmd = buildDbCommands(opts).find((c) => c.verb === verb)

      expect(() => cmd?.buildArgs(opts)).toThrow(new RegExp(`${verb}Script`))
    })
  }
})
