/**
 * Regenerates `integration/.env.example` from the service registry.
 *
 * Generated rather than hand-kept for one reason: a hand-kept example drifts,
 * and the failure is silent — a variable the code reads but the example never
 * mentioned looks like a missing credential nobody documented. The registry is
 * what the suites actually read, so it is also what the example must come from.
 *
 *   pnpm --filter @theokit/plugins-integration env:example
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

import { RUN_SWITCH_VAR, SERVICES, type ServiceSpec } from '../src/services.js'

/**
 * The full text of `.env.example` for a registry.
 *
 * Pure, and exported, so the drift gate can compare the committed file against it without
 * running the generator — a gate that regenerated the file before comparing would agree with
 * itself no matter what was committed.
 */
export function renderEnvExample(services: readonly ServiceSpec[]): string {
  const lines: string[] = [
    '# Live E2E credentials — copy to integration/.env and fill in what you have.',
    '#',
    '# GENERATED by `pnpm --filter @theokit/plugins-integration env:example`. Edit',
    '# integration/src/services.ts, not this file.',
    '#',
    `# Nothing runs without ${RUN_SWITCH_VAR}=1, so a stray \`pnpm integration\` cannot spend money`,
    '# or send email. Every variable is optional: a service whose credentials are',
    '# absent SKIPS with a named reason instead of failing.',
    '',
    `${RUN_SWITCH_VAR}=0`,
    '',
  ]

  for (const spec of services) {
    lines.push(`# ── ${spec.label} — ${spec.pkg} (via ${spec.provider}, ${spec.exercise})`)
    if (spec.caveat !== undefined) lines.push(`# ⚠ ${spec.caveat}`)
    for (const cred of [...spec.credentials, ...spec.target]) {
      lines.push(`#   ${cred.what}`)
      lines.push(`#   ↳ ${cred.where}`)
      lines.push(`${cred.name}=`)
    }
    for (const cred of spec.optionalCredentials ?? []) {
      lines.push(`#   OPTIONAL — ${cred.what}`)
      lines.push(`#   ↳ ${cred.where}`)
      lines.push(`${cred.name}=`)
    }
    lines.push('')
  }

  return lines.join('\n')
}

// Written only when this file IS the entry point. The drift gate imports it, and an import
// that wrote the file would make the comparison vacuous.
if (process.argv[1] !== undefined && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const target = join(import.meta.dirname, '..', '.env.example')
  writeFileSync(target, renderEnvExample(SERVICES))
  process.stdout.write(`wrote ${target} (${SERVICES.length} services)\n`)
}
