/**
 * Regenerates `integration/.env.example` from the service registry.
 *
 * Generated rather than hand-kept for one reason: a hand-kept example drifts,
 * and the failure is silent — a variable the code reads but the example never
 * mentioned looks like a missing credential nobody documented. The registry is
 * what the suites actually read, so it is also what the example must come from.
 *
 *   pnpm --filter @theokit/plugins-integration env:example
 */

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { RUN_SWITCH_VAR, SERVICES } from '../src/services.js'

const lines: string[] = [
  '# Live E2E credentials — copy to integration/.env and fill in what you have.',
  '#',
  '# GENERATED by `pnpm --filter @theokit/plugins-integration env:example`. Edit',
  '# integration/src/services.ts, not this file.',
  '#',
  `# Nothing runs without ${RUN_SWITCH_VAR}=1, so a stray \`pnpm integration\` cannot spend money`,
  '# or send email. Every variable is optional: a service whose credentials are',
  '# absent SKIPS with a named reason instead of failing.',
  '',
  `${RUN_SWITCH_VAR}=0`,
  '',
]

for (const spec of SERVICES) {
  lines.push(`# ── ${spec.label} — ${spec.pkg} (via ${spec.provider}, ${spec.exercise})`)
  if (spec.caveat !== undefined) lines.push(`# ⚠ ${spec.caveat}`)
  for (const cred of [...spec.credentials, ...spec.target]) {
    lines.push(`#   ${cred.what}`)
    lines.push(`#   ↳ ${cred.where}`)
    lines.push(`${cred.name}=`)
  }
  for (const cred of spec.optionalCredentials ?? []) {
    lines.push(`#   OPTIONAL — ${cred.what}`)
    lines.push(`#   ↳ ${cred.where}`)
    lines.push(`${cred.name}=`)
  }
  lines.push('')
}

const target = join(import.meta.dirname, '..', '.env.example')
writeFileSync(target, lines.join('\n'))
process.stdout.write(`wrote ${target} (${SERVICES.length} services)\n`)
